#!/usr/bin/env python3
"""Verify vendored wordlists and generate their C++ embedding header."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import re
import sys


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SOURCE = PROJECT_ROOT / "third_party" / "bip39" / "english.txt"
OUTPUT = (
    PROJECT_ROOT
    / "include"
    / "arborkdf"
    / "generated"
    / "bip39_english_wordlist.hpp"
)
EXPECTED_SHA512 = (
    "416c71ba30018ea292bb36cdc23c9329673485a8d8933266a9d9a7cc72153b8b"
    "aed3d430f52eab4f5d3addf6583611b3777a50454599f1e42716f5f879621123"
)
EXPECTED_COMMIT = "b9f9a8d6e854fa0b0c8f818753420b0aa6e875aa"
EXPECTED_GIT_BLOB = "942040ed50f7205cafc465496229128ba4f78e75"
EXPECTED_WORD_COUNT = 2048
WORD_PATTERN = re.compile(r"[a-z]+", re.ASCII)


def read_and_verify_words() -> list[str]:
    raw = SOURCE.read_bytes()
    actual_sha512 = hashlib.sha512(raw).hexdigest()
    if actual_sha512 != EXPECTED_SHA512:
        raise ValueError(
            f"{SOURCE}: SHA-512 mismatch; expected {EXPECTED_SHA512}, "
            f"got {actual_sha512}"
        )
    try:
        text = raw.decode("ascii")
    except UnicodeDecodeError as error:
        raise ValueError(f"{SOURCE}: canonical English list is not ASCII") from error
    if not text.endswith("\n") or "\r" in text:
        raise ValueError(f"{SOURCE}: expected canonical LF line endings and final LF")

    words = text[:-1].split("\n")
    if len(words) != EXPECTED_WORD_COUNT:
        raise ValueError(
            f"{SOURCE}: expected {EXPECTED_WORD_COUNT} words, got {len(words)}"
        )
    if any(WORD_PATTERN.fullmatch(word) is None for word in words):
        raise ValueError(f"{SOURCE}: expected one lowercase ASCII word per line")
    if len(set(words)) != len(words):
        raise ValueError(f"{SOURCE}: duplicate word")
    if words != sorted(words):
        raise ValueError(f"{SOURCE}: words are not sorted")
    if len({word[:4] for word in words}) != len(words):
        raise ValueError(f"{SOURCE}: first four characters are not unique")
    return words


def make_header(words: list[str]) -> str:
    entries = "\n".join(f'    std::string_view{{"{word}"}},' for word in words)
    return f"""// Generated by extras/gen_wordlist_header.py. Do not edit.
// Source: bitcoin/bips bip-0039/english.txt
// Upstream commit: {EXPECTED_COMMIT}
// Upstream Git blob: {EXPECTED_GIT_BLOB}
// Source SHA-512: {EXPECTED_SHA512}
#pragma once

#include <array>
#include <string_view>

namespace arborkdf::generated {{

inline constexpr std::string_view kBip39EnglishSelector{{"embedded_bip39"}};
inline constexpr std::array<std::string_view, {EXPECTED_WORD_COUNT}U>
    kBip39EnglishWords{{{{
{entries}
}}}};

static_assert(kBip39EnglishWords.size() == {EXPECTED_WORD_COUNT}U);

}}  // namespace arborkdf::generated
"""


def check_header(expected: str) -> None:
    try:
        actual = OUTPUT.read_bytes()
    except FileNotFoundError as error:
        raise ValueError(
            f"{OUTPUT}: generated header is missing; run "
            "python3 extras/gen_wordlist_header.py"
        ) from error
    if actual != expected.encode("utf-8"):
        raise ValueError(
            f"{OUTPUT}: generated header is stale; run "
            "python3 extras/gen_wordlist_header.py"
        )


def write_header(contents: str) -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    temporary = OUTPUT.with_name(OUTPUT.name + ".tmp")
    try:
        with temporary.open("w", encoding="utf-8", newline="\n") as stream:
            stream.write(contents)
        os.replace(temporary, OUTPUT)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "verify the pinned BIP-39 English source and generate its C++ header"
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the source digest and that the committed header is current",
    )
    arguments = parser.parse_args()
    try:
        expected = make_header(read_and_verify_words())
        if arguments.check:
            check_header(expected)
        else:
            write_header(expected)
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
